# Generated by Django 5.0.6 on 2024-07-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
