# Generated by Django 5.0.6 on 2024-08-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_asset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
