# Generated by Django 5.0.6 on 2024-08-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_scrapedvulnerability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionhistory',
            name='state_on_change_date',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Assigned', 'Assigned'), ('In Remediation', 'In Remediation'), ('Remediated', 'Remediated'), ('In Verification', 'In Verification'), ('Verified', 'Verified'), ('Closed', 'Closed')], max_length=40),
        ),
        migrations.AlterModelTable(
            name='scrapedvulnerability',
            table='ScrapedVulnerability',
        ),
    ]
